.fedora.latest.template: &fedora_template
  image: fedora:latest
  before_script:
    - dnf install -y GeoIP-devel make gcc

fedora.simple:
  <<: *fedora_template
  script:
    - USE_GEOIP=no USE_DYN_GEOIP=no CFLAGS="-O2 -g -Werror" make
    - make check

fedora.geoip:
  <<: *fedora_template
  script:
    - USE_GEOIP=yes USE_DYN_GEOIP=no CFLAGS="-O2 -g -Werror" make
    - make check

fedora.dyn_geoip:
  <<: *fedora_template
  script:
    - USE_GEOIP=yes USE_DYN_GEOIP=yes CFLAGS="-O2 -g -Werror" make
    - make check

