.fedora.latest.template: &fedora_template
  image: fedora:latest
  before_script:
    - dnf install -y GeoIP-devel libmaxminddb-devel make gcc

fedora.simple:
  <<: *fedora_template
  script:
    - USE_GEOIP=no USE_RUNTIME_LINKING=no CFLAGS="-O2 -g -Werror" make
    - make check

fedora.geoip:
  <<: *fedora_template
  script:
    - USE_GEOIP=yes USE_RUNTIME_LINKING=no USE_MAXMIND=no CFLAGS="-O2 -g -Werror" make
    - make check

fedora.dyn_geoip:
  <<: *fedora_template
  script:
    - USE_GEOIP=yes USE_RUNTIME_LINKING=yes USE_MAXMIND=no CFLAGS="-O2 -g -Werror" make
    - make check

fedora.maxmind:
  <<: *fedora_template
  script:
    - USE_GEOIP=no USE_RUNTIME_LINKING=no USE_MAXMIND=yes CFLAGS="-O2 -g -Werror" make
    - make check

fedora.dyn_maxmind:
  <<: *fedora_template
  script:
    - USE_GEOIP=no USE_RUNTIME_LINKING=yes USE_MAXMIND=yes CFLAGS="-O2 -g -Werror" make
    - make check
